In [2]:
import pandas as pd
from pandas import read_csv
from pandas import datetime
from matplotlib import pyplot
import matplotlib.pyplot as plt
from scipy import interpolate

def parser(x):
    return datetime.strptime('201'+x, '%m/%d/%Y')

series = pd.read_csv(r'C:\Users\Martina\Google Drive\tide_induced_gw_level\spreadsheets\stages\s27_t_2018_2020.csv', header=0) 
series

C:\Users\Martina\AppData\Local\Continuum\Anaconda3\Lib\site-packages\ipykernel_launcher.py:3: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  This is separate from the ipykernel package so we can avoid doing imports until

         index              date  year  month  day  hour  tide
0            1     1/1/2018 0:00  2018      1    1     0  0.23
1            2     1/1/2018 0:03  2018      1    1     0  0.21
2            3     1/1/2018 0:05  2018      1    1     0  0.18
3            4     1/1/2018 0:08  2018      1    1     0  0.16
4            5     1/1/2018 0:12  2018      1    1     0  0.13
...        ...               ...   ...    ...  ...   ...   ...
520801  520802  12/31/2020 23:45  2020     12   31    23  1.69
520802  520803  12/31/2020 23:46  2020     12   31    23  1.66
520803  520804  12/31/2020 23:51  2020     12   31    23  1.64
520804  520805  12/31/2020 23:52  2020     12   31    23  1.62
520805  520806  12/31/2020 23:57  2020     12   31    23  1.60

[520806 rows x 7 columns]

In [3]:
format = '%m/%d/%Y %H:%M'
series['datetime'] = pd.to_datetime(series['date'] , format=format)
series = series.set_index(pd.DatetimeIndex(series['datetime']))
series1 = series['tide'].resample(rule='H').mean().interpolate(method='cubic', order=3)
series1 = series1.reset_index()
series1['tide'] = (series1['tide']-1.52) # from ft NGVD to meters NAVD
series1.to_csv(r'C:\Users\Martina\PROJECTS\Jacobs model\test.csv') 
print(series1)
#plt.plot(series1)

                 datetime      tide
0     2018-01-01 00:00:00 -1.401429
1     2018-01-01 01:00:00 -1.727143
2     2018-01-01 02:00:00 -1.905000
3     2018-01-01 03:00:00 -1.917500
4     2018-01-01 04:00:00 -1.348966
...                   ...       ...
26299 2020-12-31 19:00:00 -0.410000
26300 2020-12-31 20:00:00  0.045833
26301 2020-12-31 21:00:00  0.431818
26302 2020-12-31 22:00:00  0.515556
26303 2020-12-31 23:00:00  0.275909

[26304 rows x 2 columns]